schema_id: schema_1790_50plus
label: "US 1790 (50+ open)"
bins:
  - [0, 4]
  - [5, 9]
  - [10, 14]
  - [15, 19]
  - [20, 24]
  - [25, 29]
  - [30, 34]
  - [35, 39]
  - [40, 44]
  - [45, 49]
  - [50, null]   # null = open interval
